### ISSUE TITLE
Drops too many items from TP Event when using ShareSuite

### ISSUE THREAD

**Issue by Schlenkat** [6thmoon/MultitudesDifficulty#4]
ShareSuite gives each player a copy of each item picked up. To balance this, it only spawns items as if there is one player. However, this mod seems to force extra items even if Extra Item Rewards is set to false.

**Comment by 6thmoon** [comment]
Please provide your **ShareSuite** configuration file.

**Comment by Schlenkat** [comment]
[com.funkfrog_sipondo.sharesuite.txt](https://github.com/6thmoon/MultitudesDifficulty/files/14235215/com.funkfrog_sipondo.sharesuite.txt)

had to save as .txt to upload

**Comment by 6thmoon** [comment]
Thank you; I should have asked, though - are you the host?

You will get extra teleporter items if *OverrideBossLootScaling* is set to **false** in `com.funkfrog_sipondo.sharesuite.cfg`, due to an error with their code.

**Comment by Schlenkat** [comment]
Yes, I host. It looks like _OverrideBossLootScaling_ is set to **true**.

For context, we play with both mods installed. When we have 3 players and select Monsoon, the TP Event drops one item. When we select Multitudes (at any "player" count), it always drops one item per real player.

**Comment by 6thmoon** [comment]
Yeah didn't think so, it was simply the most plausible explanation. The original ticket seemed to suggest it dropped an extra item for each additional (not real) player, thank you for clarifying.

I expect this will strike you as a odd suggestion, but if you set *Extra Item Rewards* to **true** in `local.difficulty.multitudes.cfg` it should fix the issue. Next update I'll handle this edge case but that looks to be an easy workaround for now.

**Comment by Schlenkat** [comment]
That worked, thanks!

**Comment by 6thmoon** [comment]
Good to hear. Appreciate the detailed report and responses.
