### ISSUE TITLE
Still not working after SotS update

### ISSUE THREAD

**Issue by Westyeti** [6thmoon/MultitudesDifficulty#6]
I tried reinstalling on r2modman but it didn't work

**Comment by 6thmoon** [comment]
Please elaborate, or provide a log file. As evidenced [here](https://github.com/6thmoon/MultitudesDifficulty/issues/5#issuecomment-2323482630), other people (not just myself) have been able to use it successfully.

**Comment by Westyeti** [comment]
how do I do that?

**Comment by 6thmoon** [comment]
If you go to *Settings* in **r2modman** there's an button under *Locations* labeled *Browse profile folder*. In the `BepInEx` subdirectory there is a file `LogOutput.log` however, note that it will be overwritten each time the game is launched.

Is the difficulty option not appearing in the lobby? Have you made any changes to the configuration file.

**Comment by 6thmoon** [comment]
Closing this since it has been a couple of weeks. Feel free to comment if you have any relevant information and I'll re-open the issue.
