### ISSUE TITLE
Lobby UI issue

### ISSUE THREAD

**Issue by Sciti** [6thmoon/MultitudesDifficulty#8]
Is it possible to add items to queue while running?

**Comment by 6thmoon** [comment]
Hello, glad you found the solution to your other issue. Are you sure this is the intended recipient for the query above?

**Comment by Sciti** [comment]
Yes, there's also a bug with difficulty selection screen
![image](https://github.com/user-attachments/assets/a7f4fe9d-9032-487c-8f18-7d7e893274e8)
About query above, when i press tab while running, hovering over items in query selection screen stops character... 
![command_queue](https://github.com/user-attachments/assets/be41f67d-5978-44eb-8b8f-ff840bd5149e)

**Comment by Sciti** [comment]
oh wait... now i understand. sorry.

**Comment by 6thmoon** [comment]
Thank you for reporting the lobby issue, though. I'll look into a solution since this seems to be affecting any other difficulties added since the *Seekers of the Storm* update.
